### ISSUE TITLE
Importing GCD Project Avg Bed Long Profile Error

### ISSUE THREAD

**Issue by philipbaileynar** [NorthArrowResearch/xsviewer-issues#25]
Attempted to import GCD project for Slughter Gulch into empty XS Viewer database and got this error:

```
------------------------------------------------
EXCEPTION
Error building Cross Section Viewer long profiles
 --- Stacktrace --- 
   at xslib.Controllers.GCD.ProjectImporter.Run(FileInfo gcdProject) in D:\Code\xsviewer\xslib\Controllers\GCD\ProjectImporter.cs:line 91
   at CrossSectionViewer.frmMain.importGCDProjectToolStripMenuItem_Click(Object sender, EventArgs e) in D:\Code\xsviewer\CrossSectionViewer\frmMain.cs:line 625
 --- Exception Data --- 
Cross Section Viewer = 2.0.13.0Sequence contains no elements
 --- Stacktrace --- 
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at xslib.Controllers.LongProfileGeneratorAvergeBed.InsertLongProfileStations(SQLiteCommand comInsert, SQLiteParameter pCrossSectionSurveyID, SQLiteParameter pStation, SQLiteParameter pElevation) in D:\Code\xsviewer\xslib\Controllers\LongProfile\LongProfileGeneratorAvergeBed.cs:line 80
   at xslib.Controllers.LongProfileGeneratorBase.Run() in D:\Code\xsviewer\xslib\Controllers\LongProfile\LongProfileGeneratorBase.cs:line 104
   at xslib.Controllers.GCD.ProjectImporter.BuildLongProfiles(LinearExtraction le) in D:\Code\xsviewer\xslib\Controllers\GCD\ProjectImporter.cs:line 103
   at xslib.Controllers.GCD.ProjectImporter.Run(FileInfo gcdProject) in D:\Code\xsviewer\xslib\Controllers\GCD\ProjectImporter.cs:line 83
Windows: Microsoft Windows NT 6.2.9200.0
Date: 10/18/2018 11:59:58 AM
```

**Comment by philipbaileynar** [comment]
Fixed for next version
